# Generated by Django 4.2.6 on 2023-12-16 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_map_mall_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_image', models.ImageField(upload_to='shop_icons/')),
                ('x', models.DecimalField(decimal_places=6, max_digits=9)),
                ('y', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.RenameField(
            model_name='mall',
            old_name='mall_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='city',
            name='malls',
        ),
        migrations.RemoveField(
            model_name='mall',
            name='map',
        ),
        migrations.AddField(
            model_name='mall',
            name='cities',
            field=models.ManyToManyField(related_name='malls', to='users.city'),
        ),
        migrations.DeleteModel(
            name='Map',
        ),
        migrations.AddField(
            model_name='shop',
            name='mall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='users.mall'),
        ),
    ]
